### ISSUE TITLE
Mélange impossible dans le TP 2

### ISSUE THREAD

**Issue by nponsard** [pbastide/do3-dataviz#20]
Dans le TP 2, partie **Mélanges** il est demandé de faire un graphique avec : 
> Températures en y, un type de ligne différent pour chaque ville, et une couleur pour chaque mois.

Or il est impossible de faire un graphique avec une variation de couleur sur des lignes pointillées.

En faisant le code suivant : 
```r
ggplot(
    data = temps_average,
    aes(x = day_of_year, y = temperature)
) +
    geom_line(aes(color = month, linetype = city)) +
    ggtitle("Températures ")
```

J’obtiens l’erreur suivante : 
```
Error in `f()`:
! geom_path: If you are using dotted or dashed lines, colour, size and linetype must be constant over the line
Backtrace:
  1. base::cat(...)
  2. rmarkdown::render(...)
  3. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  4. knitr:::process_file(text, output)
  7. knitr:::process_group.block(group)
     ...
 34. ggplot2 f(..., self = self)
 35. base::lapply(...)
 36. ggplot2 FUN(X[[i]], ...)
 38. ggplot2 `<ggprt_mt>`(data, panel_params, coord, na.rm = FALSE)
 39. ggplot2 f(...)
```

**Comment by pbastide** [comment]
C'est vrai que le message d'erreur n'est pas très informatif ici.
Le problème vient du fait qu'il faut transformer le `month` en un facteur (variable discrète), pour qu'il soit bien pris en compte par `ggplot`.
Le code suivant devrait fonctionner :
```r
ggplot(
    data = temps_average,
    aes(x = day_of_year, y = temperature)
) +
    geom_line(aes(color = as.factor(month), linetype = city)) +
    ggtitle("Températures ")
```

Il est aussi de bonne pratique de définir toutes les `aes` lors du premier appel. Le code suivant est donc équivalent :
```r
ggplot(temps_average,
       aes(x = day_of_year,
           y = temperature,
           linetype = city,
           color = as.factor(month))) +
  geom_line() +
  ggtitle("Températures ")
```

**Comment by nponsard** [comment]
En effet, en mettant en facteur le mois le code fonctionne, merci.
